# -*- coding: utf-8 -*-
"""CREDIT LOAN ANALYSIS PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvD_jc1CGuaalC9Ss-MbZGljSNd-7vOO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/cleaned_loan_data.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

#REMOVE DUPLICTAES
df=df.drop_duplicates()

#HANDLE MISSING VALUES
df=df.dropna().copy()

#CREATING NEW COLUMNS
#INCOME GROUP
def income_group(income):
    if income < 30000:
        return "Low"
    elif income < 70000:
        return "Medium"
    else:
        return "High"

df["IncomeGroup"] = df["Income"].apply(income_group)

def credit_category(score):
    if score < 600:
        return "Poor"
    elif score < 750:
        return "Average"
    else:
        return "Good"

df["CreditCategory"] = df["CreditScore"].apply(credit_category)

#RISK CATEGORY
def risk_category(row):
    if row["CreditScore"] < 600 and row["Income"] < 30000:
        return "High Risk"
    elif row["CreditScore"] < 700:
        return "Medium Risk"
    else:
        return "Low Risk"

df["RiskCategory"] = df.apply(risk_category, axis=1)

"""# Exploratory Data Analysis (EDA)

"""

sns.countplot(x="LoanApproved", data=df)
plt.show()

"""# Income vs **Approval**"""

sns.boxplot(x="LoanApproved", y="Income", data=df)
plt.show()

"""# Credit Score vs **Approval**"""

sns.boxplot(x="LoanApproved", y="CreditScore", data=df)
plt.show()

"""# Risk **Distribution**"""

sns.countplot(x="RiskCategory", data=df)
plt.show()

"""# Save Cleaned **Data**"""

df.to_csv("cleaned_loan_data.csv", index=False)